<?php

$reponses = array(
	"1_1" => array("de"),
	"1_2" => array("de la"),
	"1_3" => array("du"),
	"1_4" => array("la"),
	"1_5" => array("de l&#39;"),
	"1_6" => array("un"),
	"1_7" => array("de la"),
	"1_8" => array("du"),
	"1_9" => array("un","mon"),
	"1_10" => array("une","la","ma"),
	"1_11" => array("la","sa"),
	"1_12" => array("du","de"),
	"1_13" => array("de","ses"),
	"1_14" => array("un","son"),
	"1_15" => array("[vide]"),
	"1_16" => array("la","sa"),
	"1_17" => array("le"),
	"1_18" => array("la"),
	"1_19" => array("une","la","ma"),
	"1_20" => array("d&#39;"),
	"1_21" => array("les"),
	"1_22" => array("les"),
	
	"2_1" => array("ait fini","finisse"),
	"2_2" => array("mette"),
	"2_3" => array("soit","f&ucirc;t"),
	"2_4" => array("puisse"),
	"2_5" => array("devienne"),
	"2_6" => array("correspond","correspondrait","correspondait"),
		
	"3_1" => array("faisait"),
	"3_2" => array("arrivait","n&#39;arrivait"),
	"3_3" => array("s&#39;est lev&eacute;"),
	"3_4" => array("est all&eacute;"),
	"3_5" => array("&eacute;tait"),
	"3_6" => array("a commenc&eacute;"),
	"3_7" => array("lisait"),
	"3_8" => array("a entendu"),
	"3_9" => array("&eacute;tait","a &eacute;t&eacute;"),
	"3_10" => array("dormait"),
	"3_11" => array("s&#39;est dirig&eacute;"),
	"3_12" => array("a ouverte"),
	"3_13" => array("s&#39;est trouv&eacute;"),
	"3_14" => array("rentrait"),
	"3_15" => array("s&#39;est excus&eacute;"),
	"3_16" => array("a expliqu&eacute;"),
	"3_17" => array("avait oubli&eacute;"),
	"3_18" => array("avait vu"),
	"3_19" => array("s&#39;&eacute;tait permis"),
	"3_20" => array("a invit&eacute;"),
		
	"4_1" => array("le"),
	"4_2" => array("la"),
	"4_3" => array("le"),
	"4_4" => array("lui"),
	"4_5" => array("en"),
	"4_6" => array("m&#39;"),
	"4_7" => array("elle"),
	"4_8" => array("lui"),
	"4_9" => array("moi"),
	"4_10" => array("y"),
		
	"5_1" => array("qui"),
	"5_2" => array("o&ugrave;","comment "),
	"5_3" => array("ce que"),
	"5_4" => array("auxquelles"),
	"5_5" => array("que"),
	"5_6" => array("lesquels"),
	"5_7" => array("dans lesquels","o&ugrave;"),
	"5_8" => array("ce dont"),
	"5_9" => array("d&#39;o&ugrave;"),
	"5_10" => array("dont"),
		
	"6_1" => array("ans"),
	"6_2" => array("pour","&agrave;"),
	"6_3" => array("pos&eacute;"),
	"6_4" => array("rapide"),
	"6_5" => array("tenir compte"),
	"6_6" => array("de suite"),
	"6_7" => array("s&#39;&eacute;claircir"),
	"6_8" => array("ainsi"),
	"6_9" => array("les deux premiers"),
	"6_10" => array("&agrave; &ecirc;tre recrut&eacute;"),
		
	"7_1" => array("ai achet&eacute;"),
	"7_2" => array("s&#39;est fait"),
	"7_3" => array("s&#39;est bless&eacute;e"),
	"7_4" => array("s&#39;est cass&eacute;"),
	"7_5" => array("se sont parl&eacute;"),
	"7_6" => array("ne se sont pas encore vus")
);

?>